//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidenta_Studenti.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Studenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studenti()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int id { get; set; }
        public string Nume { get; set; }
        public Nullable<System.DateTime> DataNasterii { get; set; }
        public string Gen { get; set; }
        public Nullable<int> An { get; set; }
        public string Nivel { get; set; }
        public string Specializarea { get; set; }
        public string Adresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [Browsable(false)] public virtual ICollection<Note> Notes { get; set; }
    }
}
